version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/web-approval/Web/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "NUGET"
      include: "scope"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10